<form action={SaveLetters}>
  <label>
    a:
    <input type="number" name="a" />
  </label>
  <label>
    b:
    <input type="number" name="b" />
  </label>
  <label>
    c:
    <input type="number" name="c" />
  </label>
  <label>
    d:
    <input type="number" name="d" />
  </label>
  <label>
    e:
    <input type="number" name="e" />
  </label>
  <label>
    f:
    <input type="number" name="f" />
  </label>
  <label>
    g:
    <input type="number" name="g" />
  </label>
  <label>
    h:
    <input type="number" name="h" />
  </label>
  <label>
    i:
    <input type="number" name="i" />
  </label>
  <label>
    j:
    <input type="number" name="j" />
  </label>
  <label>
    k:
    <input type="number" name="k" />
  </label>
  <label>
    l:
    <input type="number" name="l" />
  </label>
  <label>
    m:
    <input type="number" name="m" />
  </label>
  <label>
    n:
    <input type="number" name="n" />
  </label>
  <label>
    o:
    <input type="number" name="o" />
  </label>
  <label>
    p:
    <input type="number" name="p" />
  </label>
  <label>
    q:
    <input type="number" name="q" />
  </label>
  <label>
    r:
    <input type="number" name="r" />
  </label>
  <label>
    s:
    <input type="number" name="s" />
  </label>
  <label>
    t:
    <input type="number" name="t" />
  </label>
  <label>
    u:
    <input type="number" name="u" />
  </label>
  <label>
    v:
    <input type="number" name="v" />
  </label>
  <label>
    w:
    <input type="number" name="w" />
  </label>
  <label>
    x:
    <input type="number" name="x" />
  </label>
  <label>
    y:
    <input type="number" name="y" />
  </label>
  <label>
    z:
    <input type="number" name="z" />
  </label>
  <button type="submit">Save</button>
</form>;
